### ISSUE TITLE
[Domains] Impossible to disable a custom certificate

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-scalingo#249]
```
scalingo --app my-app domains-ssl my.example.com disable
```

Does not do anything.

The disable method remove the certificate from the model. This is done by setting the tlscert and tlskey to the empty string. However in go-scalingo this struct does have an omitempty attribute. So the empty value is never sent and the certificate is never disabled.

Setting this to high as currently our dashboard does not allow to do this action. The CLI is the only way to do that.

**Comment by EtienneM** [comment]
@johnsudaar I actually don't understand why you said that there is no `omitempty` for `tlscert` and `tlskey`:

https://github.com/Scalingo/go-scalingo/blob/a135a0869219c13d75af0a3b9a18933b0cfbb541/domains.go#L49-L50

Did I misunderstood what you mentioned in your Slack message?

**Comment by johnsudaar** [comment]
I said that there is one! That's the issue because when we try to remove the cert and key we set them to the empty string. So when serialized the object won't contain those keys and the patch request will contain an empty JSON (so it will be a noop).
