### ISSUE TITLE
Add ability to cache the scalingo http clients

### ISSUE THREAD

**Issue by francois2metz** [Scalingo/go-scalingo#314]
I was debugging some issues with the [steampipe plugin](https://github.com/francois2metz/steampipe-plugin-scalingo) regarding access token. I saw that, in theory, the `ScalingoAPI` and others such as `AuthAPI` and with more work the `DBAPI`  could be cached to avoid requesting new access tokens for instance. It's only used in tests for now and not exposed to the public. 
Do you think that it would make sense to expose it to the public? I believe it would improve the performance of the plugin and remove some load on the API.

**Comment by guillaume-sc** [comment]
Thank you for taking the time to share your suggestion, @francois2metz.

The change you propose would turn Scalingo HTTP clients from being stateless to being stateful. Caching the JWT tokens would require clients have the capability of renewing tokens when they expire. There could be other changes necessary that I’m not thinking about right now.

Such change is not on our roadmap, however we accept external contributions for such optimizations.

**Comment by francois2metz** [comment]
> The change you propose would turn Scalingo HTTP clients from being stateless to being stateful. Caching the JWT tokens would require clients have the capability of renewing tokens when they expire. There could be other changes necessary that I’m not thinking about right now.

It seems that be already stateful, see https://github.com/Scalingo/go-scalingo/blob/fe2ab27610dfdf8f9bf343f81fe753b95d479803/http/api_token_generator.go#L35-L58

I'll send a PR to see if it works.
