### ISSUE TITLE
[MAINTENANCE-WINDOWS | STORY-64] Add the new maintenance events

### ISSUE THREAD

**Issue by SCedricThomas** [Scalingo/go-scalingo#354]
Related to [STORY-64](https://www.notion.so/scalingooriginal/STORY-64)

**Comment by ipfaze** [comment]
@yohann-bacha is this issue still under `Staging`?
If yes, could you add a cycle to it please 🙏

**Comment by yohann-bacha** [comment]
@ipfaze I think we were two to select the next cycle: it removed it :smile: done
